services:
    kizilare.source_processor:
        class: Kizilare\ServicesDebug\Processor\SourceProcessor
        arguments:
          - '%kernel.root_dir%'
    kizilare.vendor_processor:
        class: Kizilare\ServicesDebug\Processor\VendorProcessor
        arguments:
          - '%kernel.root_dir%'
    kizilare.methods_processor:
        class: Kizilare\ServicesDebug\Processor\MethodsProcessor
        arguments:
          - '%kernel.root_dir%'
    kizilare.dependency_holder:
        class: Kizilare\ServicesDebug\Helper\DependenciesHolderHelper
    kizilare.graph_processor:
        class: Kizilare\ServicesDebug\Processor\GraphProcessor
    kizilare.dependencies_processor:
        class: Kizilare\ServicesDebug\Processor\DependenciesProcessor
